apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-adapter
  labels:
    app: traefik-adapter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik-adapter
  template:
    metadata:
      labels:
        app: traefik-adapter
    spec:
      containers:
        - name: traefik-adapter
          image: registry.cn-qingdao.aliyuncs.com/xiangwenhai/traefik-adapter:latest
#         ports:
#           - containerPort: 8080
#          env:
#            - name: ENV_VAR_NAME
#              value: ENV_VAR_VALUE
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
      serviceAccount: traefik-adapter-sa
      serviceAccountName: traefik-adapter-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: traefik-adapter-role
rules:
  - apiGroups: ["networking.k8s.io"]
    resources: [ "ingresses"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  - apiGroups: ["traefik.io"]
    resources: ["*"]
    verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: traefik-adapter-role-binding
subjects:
  - kind: ServiceAccount
    name: traefik-adapter-sa
    namespace: <your-namespace>
roleRef:
  kind: ClusterRole
  name: traefik-adapter-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-adapter-sa
